### ISSUE TITLE
Routes does not load Data sources from gathermate2/gathermate2data

### ISSUE THREAD

**Issue by Chichi-code** [sam0x17/routes_classic#4]
I've installed the classic version of GatherMate2 (https://www.curseforge.com/wow/addons/gathermate2) and GatherMate2 data (https://www.curseforge.com/wow/addons/spinx-gathermate2-data-classic) but routes won't load them as data source. Joining associated screenshot.
![routes_wont_load PNG](https://user-images.githubusercontent.com/57328054/68090276-201cdc80-fe72-11e9-9910-1c755a267a27.jpg)

**Comment by sam0x17** [comment]
you have to use this one as all the ones on curse are broken -- follow instructions on readme page

**Comment by Chichi-code** [comment]
Unfortunately, i've already tried and it doesn't change the problem

**Comment by Chichi-code** [comment]
Seems i've got it to work ; latest version of gathermate2 and gathermate2 data (for classic) + fix on routes and delete cache and local variables before re launching the game

**Comment by sam0x17** [comment]
that makes sense, gotcha
