### ISSUE TITLE
Addon doesn't know any zones

### ISSUE THREAD

**Issue by SirJorb** [sam0x17/routes_classic#9]
Addon doesn't know any of the zones, so it doesn't work. Attempting to create a blank route (with no zone assigned) causes this error and bricks the addon any time you open it from then on:

`Message: Interface/AddOns/Routes/Routes.lua:863: bad argument #2 to 'format' (string expected, got nil)`
`Time: Wed Nov 15 10:24:16 2023`
`Count: 2`
`Stack: Interface/AddOns/Routes/Routes.lua:863: bad argument #2 to 'format' (string expected, got nil)`
`[string "=[C]"]: in function 'format'`
`[string "@Interface/AddOns/Routes/Routes.lua"]:863: in function 'member'`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:215: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164>`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:337: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:310>`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1006: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1002>`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1025: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1002>`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1059: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1036>`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1726: in function 'FeedGroup'`
`[string "@Interface/AddOns/GatherMate2/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1919: in function 'Open'`
`[string "@Interface/AddOns/Routes/Routes.lua"]:894: in function '?'`
`[string "@Interface/FrameXML/ChatFrame.lua"]:4975: in function <Interface/FrameXML/ChatFrame.lua:4921>`
`[string "=[C]"]: in function 'ChatEdit_ParseText'`
`[string "@Interface/FrameXML/ChatFrame.lua"]:4638: in function 'ChatEdit_SendText'`
`[string "@Interface/FrameXML/ChatFrame.lua"]:4674: in function 'ChatEdit_OnEnterPressed'`
`[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>`

`Locals: (*temporary) = "You have %d route(s) in %s."`
`(*temporary) = 1`
`(*temporary) = nil`
`(*temporary) = "string expected, got nil"`

**Comment by sam0x17** [comment]
Yeah this is super out of date there is now a maintained one floating around. This was done in the first few weeks of classic when nothing was up and running in the addon ecosystem yet

**Comment by SirJorb** [comment]
Do you happen to know where to find it? This was the only result I found on Google for Routes but for Classic.

**Comment by sam0x17** [comment]
https://www.curseforge.com/wow/addons/routes
